# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'track.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(718, 392)
        Form.setStyleSheet("background: rgb(30,30,30);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(400, 100))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.track0 = QtWidgets.QHBoxLayout()
        self.track0.setObjectName("track0")
        self.label_track = QtWidgets.QLabel(self.widget)
        self.label_track.setStyleSheet("color:white;")
        self.label_track.setObjectName("label_track")
        self.track0.addWidget(self.label_track)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.track0.addItem(spacerItem)
        self.comboBox_track = QtWidgets.QComboBox(self.widget)
        self.comboBox_track.setStyleSheet("background:white;\n"
"color:black;")
        self.comboBox_track.setObjectName("comboBox_track")
        self.comboBox_track.addItem("")
        self.comboBox_track.addItem("")
        self.comboBox_track.addItem("")
        self.comboBox_track.addItem("")
        self.track0.addWidget(self.comboBox_track)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.track0.addItem(spacerItem1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem2)
        self.horizontalSlider_track = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(22)
        sizePolicy.setHeightForWidth(self.horizontalSlider_track.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_track.setSizePolicy(sizePolicy)
        self.horizontalSlider_track.setMaximumSize(QtCore.QSize(90, 22))
        self.horizontalSlider_track.setStyleSheet("QSlider::groove:horizontal{\n"
"    border: 1px solid black;\n"
"    height: 3px;\n"
"    width: 50px;\n"
"    background: cyan;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    background: cyan;\n"
"    border: 1px solid black;\n"
"    width: 6px;\n"
"    margin: -8px 0;\n"
"    boder-radius: 9px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"    background-color: white;\n"
"}")
        self.horizontalSlider_track.setMaximum(127)
        self.horizontalSlider_track.setProperty("value", 64)
        self.horizontalSlider_track.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_track.setObjectName("horizontalSlider_track")
        self.verticalLayout_10.addWidget(self.horizontalSlider_track)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem3)
        self.track0.addLayout(self.verticalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.track0.addItem(spacerItem4)
        self.pushButton_mute_track = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mute_track.setFont(font)
        self.pushButton_mute_track.setStyleSheet("background:green;\n"
"color:white;")
        self.pushButton_mute_track.setObjectName("pushButton_mute_track")
        self.track0.addWidget(self.pushButton_mute_track)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.track0.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.track0)
        self.verticalLayout_3.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_track.setText(_translate("Form", "Track"))
        self.comboBox_track.setItemText(0, _translate("Form", "Teclado"))
        self.comboBox_track.setItemText(1, _translate("Form", "Flauta"))
        self.comboBox_track.setItemText(2, _translate("Form", "Guitarra Electrica"))
        self.comboBox_track.setItemText(3, _translate("Form", "Tambores"))
        self.pushButton_mute_track.setText(_translate("Form", "Mute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
