# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'track.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(718, 392)
        Form.setStyleSheet("background: rgb(30,30,30);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_Track = QtWidgets.QWidget(Form)
        self.widget_Track.setObjectName("widget_Track")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_Track)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.track0_layout = QtWidgets.QHBoxLayout()
        self.track0_layout.setObjectName("track0_layout")
        self.label_track = QtWidgets.QLabel(self.widget_Track)
        self.label_track.setStyleSheet("color:white;")
        self.label_track.setObjectName("label_track")
        self.track0_layout.addWidget(self.label_track)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.track0_layout.addItem(spacerItem)
        self.comboBox_track = QtWidgets.QComboBox(self.widget_Track)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_track.setFont(font)
        self.comboBox_track.setStyleSheet("background:white;\n"
"color:black;")
        self.comboBox_track.setObjectName("comboBox_track")
        self.comboBox_track.addItem("")
        self.comboBox_track.addItem("")
        self.comboBox_track.addItem("")
        self.comboBox_track.addItem("")
        self.track0_layout.addWidget(self.comboBox_track)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.track0_layout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalSlider_track = QtWidgets.QSlider(self.widget_Track)
        self.horizontalSlider_track.setMaximumSize(QtCore.QSize(103, 22))
        self.horizontalSlider_track.setStyleSheet("QSlider::groove:horizontal{\n"
"    border: 1px solid black;\n"
"    height: 3px;\n"
"    width: 65px;\n"
"    background: cyan;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    background: cyan;\n"
"    border: 1px solid black;\n"
"    width: 6px;\n"
"    margin: -8px 0;\n"
"    boder-radius: 9px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"    background-color: white;\n"
"}")
        self.horizontalSlider_track.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_track.setObjectName("horizontalSlider_track")
        self.verticalLayout_2.addWidget(self.horizontalSlider_track)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.track0_layout.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.track0_layout.addItem(spacerItem4)
        self.pushButton_mute_track = QtWidgets.QPushButton(self.widget_Track)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mute_track.setFont(font)
        self.pushButton_mute_track.setStyleSheet("background:green;\n"
"color:white;")
        self.pushButton_mute_track.setObjectName("pushButton_mute_track")
        self.track0_layout.addWidget(self.pushButton_mute_track)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.track0_layout.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.track0_layout)
        self.verticalLayout.addWidget(self.widget_Track)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_track.setText(_translate("Form", "Track 0"))
        self.comboBox_track.setItemText(0, _translate("Form", "Piano"))
        self.comboBox_track.setItemText(1, _translate("Form", "Tambores"))
        self.comboBox_track.setItemText(2, _translate("Form", "Guitarra Electrica"))
        self.comboBox_track.setItemText(3, _translate("Form", "Flauta"))
        self.pushButton_mute_track.setText(_translate("Form", "Mute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
